#!/usr/bin/env bash
# Script that setup a nginx web server on our server.

sudo apt -y update && apt -y upgrade
sudo apt -y install nginx
ufw allow 'Nginx HTTP'
sudo service nginx restart

echo "Holberton School" >/var/www/html/index.nginx-debian.html

sudo service nginx restart
